// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyczPKhfjTPFG-UEUnAQxg_JICjc-i4s',
    appId: '1:1068122548904:web:e3efc6074a601c7e18f09d',
    messagingSenderId: '1068122548904',
    projectId: 'parking-b55ae',
    authDomain: 'parking-b55ae.firebaseapp.com',
    storageBucket: 'parking-b55ae.firebasestorage.app',
    measurementId: 'G-9BD1FPD4F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa9XhQsqjiQR-ysWg1lRCk-TaA7HYCB60',
    appId: '1:1068122548904:android:f4ba198dbfd845e318f09d',
    messagingSenderId: '1068122548904',
    projectId: 'parking-b55ae',
    storageBucket: 'parking-b55ae.firebasestorage.app',
  );

}